import type { Metadata } from 'next';
import LocalFont from 'next/font/local';
import './globals.css';

const inter = LocalFont({ src: '../assets/fonts/Satoshi-Variable.ttf' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div id='modal'></div>
        {children}
      </body>
    </html>
  );
}
