name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #
    strategy:
      matrix:
        node: [18, 20]

    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v3
      - name: Run CI
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run lint

      - name: Run tests and generate coverage
        run: |
          npm run test &&
          npm i coverage-badges-cli -g &&
          coverage-badges --output coverage/badges.svg

      - name: Run build
        run: npm run build

      # - name: Deploy to Netlify
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: 9ef4bac7-de72-4a62-93b9-49b7666b6d01 # Replace with your Netlify site ID
      #   run: npx netlify deploy --prod --dir=build # Adjust the build directory if needed
